# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - main # ветка git

cache: node_modules # кеширование

install:
  - npm ci # установка зависимостей из package-lock.json
  # - npm install # установка зависимостей из package.json (возможно неявное обновление зависимостей)

build: off # отключение встроенной в appveyor системы сборки

build_script:
  - npm run build # сборка проекта

test_script:
  - npm run lint && npm test # скрипт тестирования
